name       : gnome-common
version    : 3.18.0
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-common/3.18/gnome-common-3.18.0.tar.xz : 22569e370ae755e04527b76328befc4c73b62bfd4a572499fde116b8318af8cf
homepage   : http://www.gnome.org/
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Common development macros for GNOME
description: |
    Common development macros for GNOME
patterns   :
    - /*
rundeps    :
    - autoconf-archive
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/aclocal/ax_{code_coverage,check_enable_debug}.m4
